server:
  port: 8081
spring:
  #controller返回页面的后缀
  freemarker:
    suffix: .html
    #不用重启项目就能刷新页面
  thymeleaf:
    cache: false
  mvc:
    static-path-pattern: /static/**
task:
  timed-task-date: 0/1 * * * * ?
scheduling:
  enabled: false   #false 关闭定时任务   #true 开启